#!/usr/bin/env python3
from pathlib import Path
import csv, io, re

ROOT=Path('.')
WBS=ROOT/'Plans/Master/WBS/master-wbs.csv'
REL=ROOT/'Plans/Master/RELATIONSHIP_INDEX.yaml'
VER=ROOT/'Plans/Master/Registers/VERIFICATION_EVIDENCE_ACCEPTANCE.md'
REQ=ROOT/'Plans/Master/Registers/REQUIREMENTS.md'
CON=ROOT/'Plans/Master/Registers/CONSTRAINTS.md'
GATES=ROOT/'Plans/Master/Registers/GATES.md'
RISKS=ROOT/'Plans/Master/Registers/RISKS.md'
DEC=ROOT/'Plans/Master/Registers/DECISIONS_TRIGGERS.md'
EXC=ROOT/'Plans/Master/Registers/EXCEPTIONS_CHANGE_CONTROLS.md'
L1=ROOT/'Plans/Master/Layers/LAYER_1_PROGRAM_ARCHITECTURE_STRATEGIC_BASELINE.md'
L4=ROOT/'Plans/Master/Layers/LAYER_4_INTEGRATED_PROGRAM_CRITICAL_PATH.md'
L5=ROOT/'Plans/Master/Layers/LAYER_5_AI_EXECUTION_EVIDENCE_STATE_CONTROL.md'
MAN=ROOT/'Plans/Master/MANIFEST.yaml'
VALIDATOR=ROOT/'Plans/Master/Tools/validate_master_plan.py'

OLD_NOTE='DEFERRED_EXCEPTION EXC-0001: account/persistence capability is not in the current accountless baseline. Mandatory authenticated/dashboard/control-plane baseline is superseded by the latest accountless-first owner decision; any reusable AdGuard/API dependency work is reintroduced separately without mandatory identity or dashboard scope.'
NEW_NOTE='DEC-0053/CR-0006: Version-1 optional parent-account, minimum persistence and lightweight dashboard/device-management scope is active. The complete core setup/protection journey remains usable without login; mandatory login for core value, browsing/activity history, child accounts and broad DNS administration are not authorised.'
ACTIVE_TRIGGER='Version-1 optional-account scope is active under DEC-0053/CR-0006; ordinary lifecycle, gate, dependency, privacy, security and precondition requirements still apply.'

updates={
'TSK-0024':{'Acceptance_Criteria':'Before LG-07, reject implementation outside the owner-authorised integrated-product-first sequence. Under DEC-0053/CR-0006, Version 1 includes optional parent account/authentication/session, minimum parent/device ownership persistence and lightweight dashboard/device management while the complete core safety setup remains usable without login. Mandatory login for core value, browsing/activity history, child accounts, broad DNS administration, GROW automation, native app, school portal, paid-acquisition system and complex safety paywalls remain excluded unless separately authorised.'},
'TSK-0025':{'Acceptance_Criteria':'CURRENT_STATE points to the centralized plan for planning/WBS authority, records the current Version-1 optional-account plus accountless-core owner decision without bypassing gates, and states that tracker/CSV artifacts remain derived until regenerated.'},
'TSK-0042':{'Acceptance_Criteria':'Requirements identify accountless setup/journey-state recovery, optional account access/session/revocation/deletion/recovery, device-configuration lifecycle, dashboard/device ownership, AdGuard/DNS integration, false-positive and unsupported-state incidents; remedies, escalation, data-minimising diagnostics, response expectations, deletion/removal/recovery and support-burden metrics are explicit.'},
'TSK-0044':{'Acceptance_Criteria':'NFRs define private/restricted AdGuard administration, secret storage/rotation, API/config timeouts/retries, partial-failure reconciliation, opaque setup/ClientID identifiers, explicit privacy booleans, version/contract regression checks, optional customer authentication/session and minimum persistence boundaries, and safe behavior when AdGuard, auth, datastore or verification paths are unavailable; no mandatory login for core value is introduced.'},
'TSK-0048':{'Acceptance_Criteria':'Backlog is dependency-ordered in small vertical slices and covers accountless public/setup surfaces, optional Google sign-in/session, minimum parent/device ownership persistence, lightweight dashboard/device management, anonymous journey state, native safeguard routing, DNS setup/verification, Protection Map, relevant external-service guidance, account/device deletion and recovery, self-service support, privacy/security tests and required operations. Mandatory login, browsing/activity history, child accounts and unrestricted DNS administration remain excluded. Each task has owner, dependencies, acceptance, tests, artifacts, size, risk and release target.'},
'TSK-0049':{'Acceptance_Criteria':'For the architecture/privacy/security/operations component of LG-07, the dual-mode Version-1 boundary is approved: accountless core plus optional parent identity/session, minimum parent/device ownership persistence and lightweight dashboard/device management; DNS/AdGuard integration uses a typed allowlisted server-side boundary; threat model, auth/authz/CSRF/IDOR, deletion/recovery, DPIA/vendor/transfer position, cost/licence assumptions, failure/recovery/observability and operations evidence have no unresolved critical threat or high privacy risk.'},
'TSK-0051':{'Acceptance_Criteria':'LG-06 has passed and all LG-07 architecture/privacy/security/operations, implementation, test, release and resource evidence passes; the first vertical slice/checkpoint preserves the accountless core and implements the approved optional Version-1 account/session/dashboard boundary with no critical blocker.'},
'TSK-0052':{'Dependencies':'TSK-0043; TSK-0321; TSK-0309; TSK-0628','Acceptance_Criteria':'LG-06 passes only if the Version-1 product/non-goals are frozen as a dual-mode baseline: the complete core setup/protection journey remains usable without login, and optional parent account, Google sign-in/session, minimum parent/device ownership persistence, lightweight dashboard/device management, account/device deletion/recovery and associated privacy/security/truth states are included. Requirements, setup/Protection-Map journey, brand/design system, content, accessibility/i18n, self-service and traceability must be internally/automatically accepted to the current L4 contract; mandatory login, browsing/activity history, child accounts and broad DNS administration remain excluded; critical conflicts are resolved. Under DEC-0052 no real-user evidence is required before this gate and none may be inferred.'},
'TSK-0053':{'Acceptance_Criteria':'LG-08 has passed; all critical acceptance evidence is current to the release, including accountless journey integrity, optional account/auth/session/ownership/dashboard isolation, DNS/AdGuard integration, privacy/deletion/removal, non-goal, recovery, self-service, accessibility and security tests; no severity-1/2 or blocking control failure remains and accepted residuals are explicit.'},
'TSK-0055':{'Acceptance_Criteria':'Traceability shows all authorised Version-1 functional requirements implemented: accountless public/setup surfaces remain usable without login; optional parent account/sign-in/session, minimum parent/device ownership persistence, lightweight dashboard/device management and account/device lifecycle are implemented; native safeguard routing, DNS activation/verification, Protection Map, relevant external-service guidance, recovery/removal and self-service support are complete. Browsing/activity history, child accounts and unrestricted DNS administration are absent; release candidate is frozen.'},
'TSK-0056':{'Acceptance_Criteria':'The integrated-acceptance component of LG-09 has passed; the production-like dual-mode Version-1 product, DNS service, optional account/session/dashboard path, accountless core path, legal/privacy/vendor/operations/support/measurement/deletion/removal/recovery evidence and rehearsal are complete; owner signs cohort/stop conditions; no participant is activated before PASS.'},
'TSK-0141':{'Acceptance_Criteria':'Every included capability maps to a current need assumption, mandatory operation/safety requirement, or explicit owner-approved product/architecture decision. Version 1 includes optional parent accounts and lightweight dashboard/device management while preserving the complete core setup/protection journey without login. Mandatory login, browsing/activity history, child accounts, unrestricted DNS administration and other advanced capabilities remain excluded unless separately reauthorised. No capability may be described as behaviorally/user validated before the L8 controlled integrated-product pilot.'},
'TSK-0146':{'Title':'Freeze Version-1 optional-account product baseline and accountless core path','Plan_Status':'PLANNED','Execution_State':'TODO','Trigger':'Applicable lifecycle/gate and all hard dependencies satisfied.','Acceptance_Criteria':'Product brief states that Version 1 includes an optional parent account and lightweight dashboard/device-management capability while the complete core setup/protection journey remains usable without login. It defines minimum identity/device persistence, authentication/session, deletion/recovery, privacy/security and failure boundaries; prohibits browsing/activity history, child accounts and broad DNS administration; and reserves any future mandatory-login expansion to explicit Project Owner authority.','Notes':'DEC-0053/CR-0006 reopens the prior accountless-only PASS because the owner now requires account capability in Version 1. Prior TSK-0146 evidence remains historical proof of the accountless-core requirement only and cannot satisfy the revised acceptance contract.'},
'TSK-0313':{'Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'Every Protection Map state has entry/evidence rules, parent-facing copy, transition rules, unsupported behavior, persistence scope and testable examples. Parent-confirmed and system-verified states are never conflated. Anonymous journey state and optional parent-owned device state are explicitly separated; account ownership never substitutes for technical verification and no browsing/query/activity history is stored.'},
'TSK-0315':{'Title':'Create the dual-mode end-to-end service blueprint for accountless core and optional parent-account lifecycle','Dependencies':'TSK-0149; TSK-0229; TSK-0142','Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'Blueprint covers discover/start, accountless setup, optional account entry/return/session, lightweight dashboard/device management, native safeguard routing, DNS activation/verification, relevant service guidance, Protection Map, false-positive/support, account/device deletion/revoke/reinstall/replacement, recovery/removal, provider outage and exit; frontstage/backstage/data/owner/failure/recovery are mapped without browsing/activity history or mandatory login.'},
'TSK-0328':{'Dependencies':'TSK-0325; TSK-0315','Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'Architecture supports normal and exception paths for the accountless core plus optional account sign-in/return/dashboard/account lifecycle, avoids unnecessary gated steps, keeps login optional for core value, and maps each screen to a user goal and requirement.'},
'TSK-0329':{'Dependencies':'TSK-0328; TSK-0312'},
'TSK-0333':{'Dependencies':'TSK-0335; TSK-0334; TSK-0146; TSK-0331; TSK-0324','Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'Prototype covers the full accountless core and optional Version-1 account paths: Google sign-in/account creation/return/session expiry/logout/delete entry, lightweight dashboard/device management, Android/iPhone DNS setup and verification, Protection Map, false-positive, support, account/device removal/revoke/reinstall/replacement/recovery, provider/error/unsupported states, responsive/mobile/RTL/accessibility and privacy boundaries. Core value never requires login; browsing/activity history and broad DNS administration are absent.'},
'TSK-0321':{'Dependencies':'TSK-0323; TSK-0324; TSK-0333','Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'Review checks every critical accountless and optional-account screen/state, including sign-in/session/dashboard/account/device lifecycle, records conformance evidence and remediation, and leaves no unresolved critical accessibility barrier.'},
'TSK-0309':{'Dependencies':'TSK-0310; TSK-0321; TSK-0187','Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'The implementation-ready Version-1 baseline is frozen only after the revised dual-mode prototype and accessibility/internal automated acceptance pass: accountless core remains usable without login; optional parent account/sign-in/session/minimum ownership persistence/lightweight dashboard and deletion/recovery paths are accepted; all critical/high functional, responsive, accessibility, privacy/security, recovery and truth-state defects are corrected and retested. Under DEC-0052 the TSK-0187 exclusion-PASS satisfies sequencing only and no user evidence is inferred.'},
'TSK-0628':{'Dependencies':'TSK-0319; TSK-0331','Plan_Status':'PLANNED','Execution_State':'WAITING','Acceptance_Criteria':'Top ordinary setup, verification, sign-in/session, dashboard/device-management, troubleshooting, recovery, account/device deletion/removal and lifecycle issues map to prevention, automatic checks, in-product help, AI assistance, safe recovery or a truthful unsupported state; human route is exceptional and bounded.'},
'TSK-0233':{'Title':'Design minimal dual-mode journey/account data model, storage, retention, and deletion flows','Acceptance_Criteria':'Each anonymous journey/session field and optional parent identity/device-ownership field maps to a requirement and lawful purpose. Anonymous state is minimised, scoped and expiring; persistent account/device data is limited to approved ownership/settings/lifecycle purposes with explicit access, retention, deletion and backup handling; no DNS/domain browsing-history store exists and core value does not require identity.'},
'TSK-0235':{'Acceptance_Criteria':'Diagrams show the public site, accountless setup application, optional Google/Firebase identity/session, minimum parent/device ownership store and lightweight dashboard, DNS activation/verification interfaces, private AdGuard administration path, direct encrypted DNS data plane, Quad9, regions/trust boundaries and excluded processors. Browser code never receives AdGuard administrative credentials and no browsing/activity history path exists.'},
'TSK-0337':{'Acceptance_Criteria':'Protection Map data contract works for anonymous journey state and, when the optional parent account is used, for the minimum authorised parent/device ownership record; verified vs parent-confirmed evidence remains separate; no browsing/query/activity history or unrestricted DNS administration is exposed.'},
'TSK-0354':{'Title':'Design the Version-1 accountless-core plus optional-account application architecture and data boundary','Acceptance_Criteria':'One production-capable Next.js application preserves the complete accountless core while supporting optional parent authentication/session, minimum parent/device ownership persistence and lightweight dashboard/device management. Architecture defines trust boundaries, session/account deletion/recovery, auth/provider/datastore failure behavior, typed AdGuard integration, no browser admin secret, no browsing/activity history and no mandatory login for core value.'},
'TSK-0355':{'Acceptance_Criteria':'ADRs fix framework/deployment/runtime boundaries, anonymous ephemeral state, minimum persistent account/device ownership store required by Version 1, authentication/session pattern, server-only AdGuard adapter, observability, backups/deletion/recovery, and explicit non-goals. Persistent data is limited to the approved account/device purpose; no browsing/activity history is introduced.'},
'TSK-0358':{'Acceptance_Criteria':'Server/browser state machine supports the complete accountless core plus optional account entry/return/expiry/logout and dashboard routing; state transitions preserve truthful evidence, recover safely from lost/expired state, and never force login for core value or persist browsing/activity history.'},
'TSK-0398':{'Title':'Verify Version-1 optional-account boundary and accountless-core availability','Acceptance_Criteria':'Build/runtime/routes/data/vendors/telemetry and end-to-end journeys prove the optional account/sign-in/session/dashboard/device-ownership capability is present and isolated while the complete core setup/protection journey remains usable without login. Cross-parent access, hidden mandatory authentication, browsing/activity history, child accounts, broad DNS administration and browser exposure of AdGuard admin credentials fail acceptance.'},
'TSK-0485':{'Acceptance_Criteria':'Threat model covers the accountless web path plus the active Version-1 account/session/dashboard surface: XSS/CSRF/session theft/account takeover, IDOR/cross-parent access, ClientID/ownership confusion, auth/provider/datastore failure, admin/API abuse, DNS amplification, dependency/supply-chain, CI/CD/secrets, deletion/recovery and privacy leakage. High/critical paths have prevention/detection/recovery controls and release-blocking tests.'},
'TSK-0497':{'Acceptance_Criteria':'Every event supports an approved purpose; accountless events remain non-identifying and optional-account events use only the minimum authorised account/device identifiers needed for security, lifecycle or product operation. No DNS/domain browsing history, child activity timeline, unnecessary identity, content payload, raw token, secret or invasive attribution exists; retention, access and deletion are explicit.'},
'TSK-0499':{'Acceptance_Criteria':'Analytics/measurement architecture supports aggregate product/service decisions and the minimum security/lifecycle signals required for optional accounts without browsing/activity history. Account/session/dashboard events are purpose-limited, access-controlled, retention-bounded and deletable; child-linked DNS/query data is never used as product analytics.'},
'TSK-0516':{'Acceptance_Criteria':'Test plan covers accountless and optional-account happy/negative paths, Google/Firebase provider failure, session expiry/revocation, authz/CSRF/IDOR/cross-parent isolation, parent/device ownership and ClientID lifecycle, deletion/recovery, DNS/configuration, Protection Map truth states, accessibility, privacy, security, rollback and proof that core value remains usable without login.'},
'TSK-0524':{'Acceptance_Criteria':'Automated end-to-end tests cover public start -> accountless setup/routing -> native safeguard guidance -> DNS setup/verification -> relevant external-service step -> Protection Map -> recovery/reinstall/remove/clear-state, plus the optional Version-1 sign-in/session/dashboard/device-management/account-deletion paths and critical failures. Tests fail on incorrect state/evidence/privacy, cross-account leakage or any hidden mandatory-login dependency for core value.'},
'TSK-0534':{'Acceptance_Criteria':'Production smoke verifies public/accountless start, optional sign-in/session/dashboard entry, one owned-device lifecycle path, DNS endpoint, Protection Map truth state, removal/recovery, privacy/security boundary, observability and rollback readiness without creating browsing/activity history or making login mandatory for core value.'}
}

# Rewrite WBS rows, activating every row whose only scope hold is the exact EXC-0001 note.
lines=WBS.read_text(encoding='utf-8-sig').splitlines()
header=next(csv.reader([lines[0]])); idx={n:i for i,n in enumerate(header)}
needed={'Task_ID','Title','Plan_Status','Execution_State','Dependencies','Trigger','Acceptance_ID','Acceptance_Criteria','Verification_ID','Verification_Method','Evidence_ID','Evidence_Required','Notes'}
assert needed <= set(idx), needed-set(idx)
changed=set(); activated=[]; olddeps={}; final={}; out=[lines[0]]
for line in lines[1:]:
    row=next(csv.reader([line])); tid=row[idx['Task_ID']]; olddeps[tid]=row[idx['Dependencies']]
    if OLD_NOTE in row[idx['Notes']]:
        row[idx['Notes']]=row[idx['Notes']].replace(OLD_NOTE,NEW_NOTE)
        if row[idx['Plan_Status']]=='DEFERRED': row[idx['Plan_Status']]='PLANNED'
        row[idx['Execution_State']]='WAITING'; row[idx['Trigger']]=ACTIVE_TRIGGER
        activated.append(tid); changed.add(tid)
    if tid in updates:
        for k,v in updates[tid].items(): row[idx[k]]=v
        changed.add(tid)
    final[tid]={k:row[i] for k,i in idx.items()}
    if tid in changed:
        s=io.StringIO(newline=''); csv.writer(s,lineterminator='').writerow(row); line=s.getvalue()
    out.append(line)
assert set(updates)<=set(final)
assert len(activated)==43, len(activated)
WBS.write_text('\n'.join(out)+'\n',encoding='utf-8')

# Synchronise VER/ACC audit rows for every changed task.
def esc(s): return str(s).replace('|','\\|')
vout=[]; seen=set()
for line in VER.read_text(encoding='utf-8').splitlines():
    m=re.match(r'^\| (TSK-\d{4}) \|',line)
    if m and m.group(1) in changed:
        r=final[m.group(1)]; tid=m.group(1)
        line='| '+' | '.join(map(esc,[tid,r['Verification_ID'],r['Verification_Method'],r['Evidence_ID'],r['Evidence_Required'],r['Acceptance_ID'],r['Acceptance_Criteria'],r['Execution_State']]))+' |'; seen.add(tid)
    vout.append(line)
assert seen==changed,(len(seen),len(changed),sorted(changed-seen)[:10])
VER.write_text('\n'.join(vout)+'\n',encoding='utf-8')

# Synchronise relationship depends_on edges only where WBS dependencies changed.
newdeps={tid:final[tid]['Dependencies'] for tid in changed if final[tid]['Dependencies']!=olddeps[tid]}
text=REL.read_text(encoding='utf-8')
for tid,deps_s in newdeps.items():
    start=text.index(f'  {tid}:\n'); m=re.search(r'^  [A-Z][A-Z0-9-]*:\n',text[start+1:],re.M); end=(start+1+m.start()) if m else len(text)
    block=text[start:end]; block=re.sub(r'    - target: TSK-\d{4}\n      type: depends_on\n','',block)
    deps=[d.strip() for d in deps_s.split(';') if d.strip()]; ins=''.join(f'    - target: {d}\n      type: depends_on\n' for d in deps)
    marker='    source: WBS/master-wbs.csv\n'; assert marker in block,tid
    block=block.replace(marker,ins+marker,1); text=text[:start]+block+text[end:]
REL.write_text(text,encoding='utf-8')

# Simple Markdown table patcher for known single-row registers.
def patch_table(path,key,patch):
    ls=path.read_text(encoding='utf-8').splitlines(); out=[]; hits=0
    for line in ls:
        if line.startswith(f'| {key} |'):
            p=[x.strip() for x in line.strip().strip('|').split('|')]
            for i,v in patch.items(): p[i]=v
            line='| '+' | '.join(p)+' |'; hits+=1
        out.append(line)
    assert hits==1,(path,key,hits); path.write_text('\n'.join(out)+'\n',encoding='utf-8')

reqs={
'REQ-0011':'Version 1 shall provide an optional parent account capability and lightweight dashboard/device management while preserving a fully usable accountless core setup/protection journey. Login shall not be required for core safety value unless a later explicit owner decision changes that rule.',
'REQ-0034':'Product requirements shall define both the accountless core path and optional Version-1 account path, including native routing, DNS, Protection Map, relevant service, account/session/dashboard/device ownership, deletion/recovery, unsupported states, help and removal without surveillance.',
'REQ-0037':'The accountless journey shall retain only minimum short-lived state with explicit expiry/clear behavior. Optional Version-1 accounts may persist only the minimum parent identity, session, device-ownership/settings and lifecycle metadata required for the approved dashboard; browsing/query/activity history is prohibited.',
'REQ-0040':'Version-1 Google/Firebase authentication architecture shall use current supported terms/quotas/pricing, data-region/transfer/subprocessor/privacy review, secure server-side session handling, provider outage/revocation/deletion behavior and migration/exit criteria; no SMS/password expansion is assumed without separate approval.',
'REQ-0041':'Optional parent authentication, minimum parent/device ownership persistence and lightweight dashboard/device management are required Version-1 scope under DEC-0053/CR-0006. The complete core safety journey must remain usable without login. Mandatory login, child accounts, browsing/activity history and unrestricted customer DNS administration remain excluded.'}
for k,v in reqs.items(): patch_table(REQ,k,{3:v})
patch_table(CON,'CON-0010',{1:'Version 1 includes optional parent accounts, minimum parent/device ownership persistence and a lightweight dashboard while the complete core safety setup remains usable without login.',2:'Mandatory login for core value requires a later explicit owner decision; account scope must remain minimum, privacy-safe and non-surveillant under DEC-0053/CR-0006.'})
patch_table(GATES,'LG-06',{3:'Freeze the dual-mode Version-1 product, brand and experience baseline: accountless core plus optional parent account/dashboard.',4:'Applicable L4 dependencies and current owner product authority satisfied under DEC-0052 and DEC-0053; LG-05 is not an active-path prerequisite.',5:'Product/non-goals; traceability; internally/automatically accepted dual-mode prototype and critical journeys; optional account/sign-in/session/dashboard/device lifecycle; accountless-core availability; brand/design system; self-service; content sources; accessibility/i18n; privacy/security boundaries; unresolved risks. No real-user evidence is required before this gate and none may be inferred.',9:'Unlocks final architecture/delivery readiness only on actual LG-06 PASS; the activated Version-1 account scope must proceed through LG-07 privacy/security/architecture controls.'})
patch_table(GATES,'LG-07',{5:'Architecture/ADRs; accountless-core plus optional identity/session/ownership/dashboard data model; auth/authz/CSRF/IDOR and deletion/recovery; Google/Firebase/vendor/privacy/transfer; typed AdGuard/ClientID integration; security/threat; measurement; test plan; recovery design; budget; delivery plan; residual risks.'})
patch_table(GATES,'LG-08',{5:'Exact release/config; accountless public/setup surfaces; optional account/sign-in/session/dashboard/device lifecycle; minimum persistence and ownership isolation; DNS integration; recovery script; CI/tests; auth/authz/IDOR/ClientID acceptance; non-goal/secret/data checks.'})

patch_table(DEC,'DEC-0009',{3:'SUPERSEDED by DEC-0053 for Version-1 account scope. Historical accountless-first product-shape decision remains traceable; the accountless core itself is retained as a required path.',4:'Superseded by explicit Project Owner instruction 2026-08-30.',5:'DEC-0053/CR-0006 governs Version-1 account scope; prior evidence remains usable only where it does not depend on excluding accounts.'})
d=DEC.read_text(encoding='utf-8'); assert '| DEC-0053 |' not in d
row='| DEC-0053 | New | Version-1 optional parent accounts with accountless core retained | ACTIVE OWNER DECISION — Version 1 must include an optional parent account capability with secure sign-in/session, minimum parent/device ownership persistence and a lightweight dashboard/device-management experience. The complete core safety setup/protection journey remains usable without login. Google/Firebase remains the planned initial authentication route subject to current L5 vendor/privacy/security verification. Mandatory login, browsing/activity history, child accounts and unrestricted DNS administration are not authorised. | Explicit Project Owner instruction 2026-08-30; supersedes DEC-0009 and activates EXC-0001 for this bounded Version-1 scope. | Reopen any prior PASS whose acceptance depended on accounts being excluded; complete account-specific L4/L5 design, privacy/security/vendor architecture, L6 implementation and L7 auth/authz/IDOR/ClientID/deletion/recovery acceptance before later gates. | Project Owner | EXC-0001; TSK-0146; TSK-0312; TSK-0142; TSK-0329; TSK-0331; TSK-0332; TSK-0333; TSK-0309; TSK-0052; TSK-0354; TSK-0356; TSK-0523; LG-06; LG-07; LG-08 | Explicit Project Owner instruction 2026-08-30; CR-0006 |\n'
pos=d.index('| DEC-0052 |'); e=d.index('\n',pos)+1; DEC.write_text(d[:e]+row+d[e:],encoding='utf-8')

patch_table(EXC,'EXC-0001',{2:'ACTIVATED_V1_SCOPE',3:'Explicit Project Owner Version-1 account requirement 2026-08-30; DEC-0053/CR-0006.',4:'Version 1 includes optional parent authentication/account, minimum parent/device ownership persistence and lightweight dashboard/device management. Core safety value remains usable without login; mandatory login, browsing/activity history, child accounts and broad DNS administration remain outside this activation.'})
e=EXC.read_text(encoding='utf-8'); assert '| CR-0006 |' not in e
cr='| CR-0006 | Project Owner | 2026-08-30 | Activate the existing optional parent-account/authentication/minimum-persistence/lightweight-dashboard branch as required Version-1 scope while retaining the complete accountless core path. | DEC-0009, EXC-0001, requirements/constraint/gates, affected WBS acceptance/dependencies/statuses, relationship index, validator, risk dispositions, Layers 1/4/5, manifest/generated/checksums, prior LG-06 readiness. | Explicit owner correction: website must be able to have accounts from Version 1. | Project Owner DEC-0053; actual privacy/security/legal/platform reality remains higher authority. | Reopen prior account-exclusion-dependent PASS; activate existing EXC-0001 tasks; require revised L4 dual-mode product/UX acceptance before LG-06, account/privacy/security architecture before LG-07, implementation before LG-08, and auth/authz/IDOR/ClientID/deletion/recovery verification in L7. | Revert only by later explicit owner decision; preserve accountless evidence and restore prior task/gate semantics from Git history if reversed. | Rebuild generated plan/checksums; run master validator and direct semantic assertions; prove 641 tasks, zero cycles/broken links, account tasks active, revised gates, preserved DEC-0052 human-validation sequence and exact GitHub read-back. | Pending publication/read-back at record creation. | ACTIVE — old LG-06 readiness superseded; no launch/publication/participant/payment authority is created. |\n'
pos=e.index('| CR-0005 |'); end=e.index('\n',pos)+1; EXC.write_text(e[:end]+cr+e[end:],encoding='utf-8')

patch_table(RISKS,'RSK-0037',{7:'Use the approved Version-1 Google/Firebase route only after current pricing/quota/terms/privacy/security verification; no SMS/Identity Platform upgrade by default; provider health/error states, revocation/deletion, migration trigger and cost headroom are required. Accountless core remains available during auth outage.',12:'Open — active Version-1 auth/vendor risk under DEC-0053/CR-0006'})
patch_table(RISKS,'RSK-0038',{7:'Server-validated identity; Secure/HttpOnly/SameSite sessions; CSRF; revocation; server-side ownership checks on every operation; opaque IDs; cross-parent negative/IDOR tests; rate/security monitoring. Release is blocked until these controls pass.',12:'Open — active release-blocking Version-1 auth/authz risk'})
patch_table(RISKS,'RSK-0040',{7:'High-entropy opaque IDs; never use ClientID as authorization; ownership constraints; idempotent provisioning; revoke/replace/reconcile lifecycle; ownership and stale-state tests. Release is blocked until these controls pass.',12:'Open — active Version-1 ClientID/ownership risk'})
patch_table(RISKS,'RSK-0041',{12:'Open — active Version-1 deletion/reconciliation risk'})
patch_table(RISKS,'RSK-0043',{12:'Open — active Version-1 dashboard scope-creep risk'})
patch_table(RISKS,'RSK-0045',{2:'Version-1 account/dashboard scope becomes mandatory for core value or expands into surveillance/complex administration beyond the bounded owner-approved optional account capability.',7:'Keep the core setup/protection journey usable without login; enforce minimum account/device data, explicit dashboard non-goals, no browsing/activity history, no child account or raw DNS policy editor, and fresh owner/privacy/security review for expansion.',8:'Remove or reduce offending scope, delete excess data if collected, restore accountless-core availability and rerun affected product/privacy/security gates.',9:'Core value requires login; new browsing/activity field appears; child account/raw DNS administration is proposed; account scope exceeds DEC-0053.',12:'Open — active scope-control risk under DEC-0053/CR-0006'})

# Constitutional and execution text.
t=L1.read_text(encoding='utf-8')
repls={
'| Accountless discovery and guided first-phone setup | Mandatory account/authentication/persistent parent dashboard (EXC-0001) |':'| Accountless discovery and guided first-phone setup | Mandatory login for core value; child accounts; broad DNS administration |\n| Optional parent account with secure sign-in, minimum parent/device persistence and lightweight dashboard/device management | Browsing/activity history or invasive monitoring |',
'| No mandatory account | Immediate accountless value is the baseline; optional persistence only after EXC-0001 trigger and full approval. |':'| Optional Version-1 account | Version 1 includes parent accounts and a lightweight dashboard; the complete core safety setup remains usable without login unless a later owner decision explicitly changes that rule. |',
'| Application | One accountless-first full-stack TypeScript + Next.js application under top-level `/website`, covering the public website and setup/product surfaces in one deployable codebase. |':'| Application | One full-stack TypeScript + Next.js application under top-level `/website`, covering the public website, accountless core setup/product path and optional Version-1 parent account/dashboard surfaces in one deployable codebase. |',
'| Application state | No application database by default; introduce persistent local storage only for a concrete validated requirement. Stripe/PayPal remain billing source of truth with only minimum reliable local references if required. |':'| Application state | Accountless journey state remains minimum and short-lived. Version-1 accounts may persist only the minimum parent identity, session, device-ownership/settings and lifecycle metadata required for the approved dashboard; no browsing/query/activity history. Stripe/PayPal remain billing source of truth with only minimum reliable local references if required. |'}
for a,b in repls.items(): assert t.count(a)==1,a; t=t.replace(a,b,1)
L1.write_text(t,encoding='utf-8')

t=L4.read_text(encoding='utf-8')
for a,b in {
'LG-06 decision -> architecture/security/privacy/delivery readiness -> LG-07 -> accountless public/setup build plus real DNS -> LG-08':'LG-06 decision -> architecture/security/privacy/delivery readiness -> LG-07 -> accountless-core plus optional parent-account/dashboard build and real DNS -> LG-08',
'DNS endpoint/platform mechanism contract -> accountless app and DNS integration architecture -> versioned DNS recovery bundle':'DNS endpoint/platform mechanism contract -> dual-mode accountless-core plus optional-account/session/dashboard and DNS integration architecture -> versioned DNS recovery bundle'}.items(): assert t.count(a)==1,a; t=t.replace(a,b,1)
L4.write_text(t,encoding='utf-8')

t=L5.read_text(encoding='utf-8'); assert '### 5.3.5 Owner-required Version-1 optional account scope' not in t
section='''### 5.3.5 Owner-required Version-1 optional account scope (DEC-0053 / CR-0006)\n\n- Effective 2026-08-30, Version 1 includes an optional parent account capability with secure authentication/session, minimum parent/device ownership persistence and lightweight dashboard/device management; the complete core safety setup/protection journey remains usable without login.\n- This activates the existing `EXC-0001` account/persistence/dashboard branch. It does not authorize browsing/query/activity history, child accounts, unrestricted DNS administration, mandatory login for core value, or a browser-visible AdGuard administration secret/control plane.\n- Prior PASS/evidence remains valid only for unchanged facts. Any PASS whose acceptance depended on accounts being excluded is reopened and re-evaluated against the revised contract.\n- Google/Firebase is the planned initial auth route, not a pre-approved production fact: current official terms, quotas/pricing, data/transfer/privacy/security behavior and failure/exit handling must be verified at the owning L5 task before architecture approval.\n- `LG-06` requires the revised dual-mode L4 product/experience baseline; `LG-07` requires account/session/data/vendor/privacy/security architecture; `LG-08` requires implementation; L7 requires auth/authz/CSRF/IDOR/ClientID/deletion/recovery acceptance. `DEC-0052/CR-0005` remains controlling for human-validation sequencing.\n- No public release, participant activation, payment, market activation or launch authority is created by this owner scope correction.\n\n'''
marker='### 5.4 Evidence and PASS rules\n'; assert t.count(marker)==1; L5.write_text(t.replace(marker,section+marker,1),encoding='utf-8')

# Manifest current change.
t=MAN.read_text(encoding='utf-8')
old='  status: 2.0-owner-frozen / OWNER_FREEZE_2026-08-27 / OWNER_TECHNICAL_COMMERCIAL_AMENDMENT_APPLIED / OWNER_LEGAL_HOLD_ACTIVE_TO_2027-08-27 / OWNER_AZURE_HANDOFF_BOUNDARY_APPLIED_2026-08-27 / POST_FREEZE_CR_0001_DEPENDENCY_REPAIR_2026-08-27 / OWNER_LEGAL_SEQUENCING_OVERRIDE_ACTIVE_TO_2027-08-27 / CR_0003_CR_0004_HISTORICAL_SEQUENCING_SUPERSEDED / OWNER_INTEGRATED_PRODUCT_FIRST_HUMAN_VALIDATION_SEQUENCE_2026-08-29 / PRE_PRODUCT_HUMAN_VALIDATION_EXCLUDED / deterministic validation pending CR-0005 execution readback'
new=old.rsplit(' / deterministic',1)[0]+' / OWNER_V1_OPTIONAL_ACCOUNT_SCOPE_2026-08-30 / deterministic validation pending CR-0006 execution readback'
assert t.count(old)==1; t=t.replace(old,new,1)
block='''post_freeze_change_control:\n  latest_change: CR-0006\n  date: '2026-08-30'\n  status: owner-required Version-1 optional parent-account scope activated while preserving the complete accountless core path; prior LG-06 readiness is superseded; canonical reliance requires deterministic validation plus GitHub publication/read-back\n  authority: explicit current Project Owner instruction 2026-08-30; DEC-0053; DEC-0052/CR-0005 remains controlling for human-validation sequencing; actual applicable safety/legal/security/privacy/platform reality remains higher authority\n  affected_scope:\n  - EXC-0001 activated for bounded Version-1 parent account/auth/session/minimum persistence/lightweight dashboard/device management\n  - prior account-exclusion-dependent L4 PASS evidence reopened for revised acceptance\n  - existing dormant account architecture/build/QA tasks activated without bypassing lifecycle or gates\n  affected_gates:\n  - LG-06 requires revised dual-mode product/brand/experience acceptance\n  - LG-07 requires active account/session/data/vendor/privacy/security architecture evidence\n  - LG-08 requires account capability implementation while preserving accountless core\n  - LG-09 remains the prerequisite to first L8 real-user validation under DEC-0052\n  semantic_delta: Version 1 has optional accounts and a lightweight dashboard; core safety value remains usable without login; mandatory login, browsing/activity history, child accounts and broad DNS administration remain excluded; old accountless-only freeze/readiness evidence is not sufficient for the revised gate\n  change_record: Registers/EXCEPTIONS_CHANGE_CONTROLS.md#post-freeze-material-change-records\n'''
t2=re.sub(r'post_freeze_change_control:\n.*?(?=generated_assembly_contract:)',block+'\n',t,flags=re.S); assert t2!=t; MAN.write_text(t2,encoding='utf-8')

# Replace superseded anti-account validator rule with the current V1 contract.
v=VALIDATOR.read_text(encoding='utf-8')
start=v.index('# specific accountless reconciliation controls')
end=v.index('# publication tree semantics')
contract='''# current Version-1 optional-account reconciliation controls\nby={r['Task_ID']:r for r in rows}\nrequired={'TSK-0146','TSK-0312','TSK-0142','TSK-0329','TSK-0331','TSK-0332','TSK-0356','TSK-0377','TSK-0394','TSK-0523'}\nfor tid in required:\n    if tid not in by: err('missing V1 account task '+tid)\n    elif by[tid]['Plan_Status']=='DEFERRED': err('V1 account task still deferred '+tid)\nfor tid in ['TSK-0187','TSK-0326','TSK-0336']:\n    if by[tid]['Plan_Status']!='NOT_APPLICABLE' or by[tid]['Execution_State']!='PASS': err('CR-0005 exclusion changed '+tid)\nif 'optional parent account' not in by['TSK-0146']['Acceptance_Criteria'].lower(): err('V1 account baseline missing')\nif 'without login' not in by['TSK-0146']['Acceptance_Criteria'].lower(): err('accountless core guarantee missing')\nif 'optional' not in by['TSK-0052']['Acceptance_Criteria'].lower(): err('LG-06 optional account contract missing')\nif 'accountless' not in by['TSK-0052']['Acceptance_Criteria'].lower(): err('LG-06 accountless core contract missing')\nif 'optional-account boundary' not in by['TSK-0398']['Title'].lower(): err('L7 optional account boundary verification missing')\nfor tid in ['TSK-0146','TSK-0052','TSK-0398','TSK-0524']:\n    a=by[tid]['Acceptance_Criteria'].lower()\n    if 'browsing/activity history' not in a and 'browsing/query/activity history' not in a: err('V1 privacy exclusion missing '+tid)\nold_note='deferred_exception exc-0001: account/persistence capability is not in the current accountless baseline'\nfor r in rows:\n    if old_note in r['Notes'].lower(): err('stale EXC-0001 task note '+r['Task_ID'])\n'''
VALIDATOR.write_text(v[:start]+contract+v[end:],encoding='utf-8')

# Evidence record.
(ROOT/'CR_0006_V1_OPTIONAL_ACCOUNT_SCOPE_EVIDENCE_2026-08-30.md').write_text(f'''# CR-0006 — Version-1 optional account scope amendment evidence\n\n**Owner authority:** explicit Project Owner instruction 2026-08-30: the website must be able to have accounts from Version 1.\n\n## Decision\nDEC-0053 activates the existing account/authentication/minimum-persistence/lightweight-dashboard branch for Version 1 while retaining a complete accountless core path. Mandatory login for core value, browsing/activity history, child accounts and unrestricted DNS administration remain excluded. DEC-0052/CR-0005 human-validation sequencing is unchanged.\n\n## Impact\n- Activated {len(activated)} existing WBS rows previously deferred solely by EXC-0001.\n- Reopened account-exclusion-dependent L4 baseline/prototype/accessibility/freeze/self-service evidence rather than fabricating equivalence.\n- Revised LG-06/LG-07/LG-08 acceptance in product -> architecture/privacy/security -> implementation order.\n- Activated existing auth/authz/IDOR/ClientID/deletion/recovery controls and updated the deterministic validator to enforce the new owner contract.\n- Preserved prior evidence for unchanged accountless-core, DNS, brand, content and other facts.\n\n## Pre-change identities\n- planning base commit: `9606d83a82f121acffdf574e9973a7a937da0990`\n- WBS blob: `f23b4f017d1baf73258fa30ecd71549bbfe1b815`\n- relationship index blob: `9ed219b4ccb6b05e68c6a264fc2b21b1008b02a4`\n- manifest blob: `1fc24e28e70c8005a75d37c1d21aecd4ea967ae5`\n- runtime blob before later reconciliation: `ad3fd01395150b802fbb025a48f7692e82b80244`\n\nCanonical reliance requires successful full validation, publication and read-back.\n''',encoding='utf-8')

print('ACTIVATED_EXC0001_TASKS='+str(len(activated)))
print('CHANGED_TASKS='+str(len(changed)))
print('DEPENDENCY_MUTATIONS='+str(len(newdeps)))
